language: php

env:
  global:
    - secure: "VzqONs/6Ih7NMCoSAtPMM5+HY1QcfBw+pPU4SC7ji/FeBfQoZ4PxCw9SG+dblPtjLdoa4Qq+XC9+UwjkwM92EIrsEz1lVutCX5paXw8KZ05+/XdHgrRqXfX1S78uDYe/NQKjjGLsotH7+8FGcw14RlVCerN0Ol7zmRQOYwvPHrggLYK2TF25rB1lwMx6ReUI6sWxXVJHoXU8jBfu6PRwfktHU/jUFu1tbZatgEknNXaDgEiwhR8UtPC6BAu3UNrsKm9z2PxXPOIRplzyJuaxosF2ljNvm4s4Agr5t1m/DjAcimID1zUpQWihlgaUvVN+Z+Gq/hloV21l7g4x2aYGh4MYIb0TOWmOWfqyux5ohKVdew79lvhZIaPsO+8TaCcD7P8g/VzEiM5Dbyz9MLZOmwmpaXO3iOO2PRjQK+ILaMTmOa2cjYFUgEpvaWGQMCK/R5Bj+nAwQhUgNptifEr1GIctgSxEosZ9HvuEaxdO0GOBfHG99PCu8PQiFH+iryrQbMRNd5HoiSbgwGxjWJOpvmc5wyp87HPLOmDa0rJ1k+y2kx871AvIAwjpworvcEiL4DhruPQxB+5WC9rnlXGzY1F3xr+aEd/P42dJli34sirOMqcbM8iG2UvhbbcAn/E9IB1QoQthYxU9ZJfn9eWFxzTNTVb+s85DAz/zaa4Vg0Q="
    - secure: "WwclyTEIEJqpfDrRZuHyXEl0IRYvMqZwCzEaakKbjZBI9U9SkbdG0t95Wqc/ul2nZeF9F5hznZshtQWpIjYntY8qjo08R0SAf6Z9AsjB6VmUL44ZNl9+5T0afoK0HY2a2RnVHXVJKL8pnzWHW1xGGK4GP+lNucguuYoO9Ky7wO/go7d5EAzM6LfNJymjRpkgIIyUU0pFtkvCvgZgz/VkgDgP4opyaAv9J7f/qG4N9Iu313GhThOpjgKIugtnRdCEkZBs7MJn8x+0JfbMaqDqYDmbHC+E3pyBfQlLN9eys5DYQ1K4AMAfvVopMo69uemPWDkHcXqRk2OJBmxdgLcg0m73KrEc/ZM2KfMPV0zHpLZitiYfYfloFn8bIabo0L5NE/3n0l3CzaaoqItKLm+uKK3z6/BDnFoAWTqZPcZy33eEuhQ/29Rf65kbL4uk6zxK0YEjVun9aDBB5+PNtn+iQywSpmptP3Dw5OgEqV9hhoh14yyPlx/Q8vsaOpivRkgaVnvfhD3QnG53wTJ3/4lsZhgFizkL1DlKN3Iyfdwgd+3bexm4et+6ao2pXfxv70cNaz+Q+mIYLUJTtH7fsFETjd+xWmTYElR7ye4leM/rYlcCq+QkWeXJZQ7SJ3MGIdgTYoWHdxzSy3n/R18ncykNrsvDAGC1T0NQRufxsgT2Dxs="

install:
  - sudo apt-get install ncftp
  - composer install

script:
  - mkdir freestyle-evaluation
  - mv data/ freestyle-evaluation/
  - mv src/ freestyle-evaluation/
  - mv vendor/ freestyle-evaluation/
  - mv templates/ freestyle-evaluation/
  - mv index.php freestyle-evaluation/

after_success:
  - ncftpput -u $FTPUSER -p $FTPPASS -R einradfahren.de /uniscience.einradfahren.de freestyle-evaluation/
